import HDP.Data.Buchberger

-- Tests whether (x4) is in the basis generated by #[-x2 * x3 + x1, -x1 * x5 + x4, x2]

open HDP.Data

def p₁ : P[Rat] := #[MTerm.mk (-1) #[0, 1, 1], MTerm.mk 1 #[1]]
def p₂ : P[Rat] := #[MTerm.mk (-1) #[1, 0, 0, 0, 1], MTerm.mk 1 #[0, 0, 0, 1]]
def p₃ : P[Rat] := #[MTerm.mk 1 #[0, 1]]

def p : P[Rat] := #[MTerm.mk 1 #[0, 0, 0, 1]]

-- Expected output:   some #[x5, 1, x3 * x5]
#eval Buchberger.idealMembership p #[p₁, p₂, p₃]
