import VerusLean.Basic
import VerusLean.Tactic.ByVerus
import VerusLean.Vstd

/-
  ------------------------------------------------------------------------------
  This file was automatically generated by the Verus-Lean pipeline.
  YOU MAY LOSE WORK IF YOU RUN THE PIPELINE AGAIN TO RE-GENERATE THIS FILE.
  Read this comment carefully to avoid this situation.

  The Verus-Lean pipeline translates Verus definitions and verification
  conditions into Lean code. If a Lean file of the same name already
  exists, then the pipeline attempts to update the existing definitions
  and theorem statements while leaving the rest of the file alone.

  Translated/updated theorem statements are tagged with a MAGIC comment.
  For best results, leave these comments alone, and don't change
  the theorem statement.
  (Definitions always get overwritten.)

  For more information about how the pipeline works, see [THIS FILE].
  ------------------------------------------------------------------------------
-/

namespace VerusLean

namespace Nonlinear

open Vstd

/- Prelude done. Place all declarations below. MAGIC COMMENT END. -/

-- example (x y z : Int) (h1 : x + 1 < y) (h2 : y < z) : x < z := by
--   grind

/- Auto-generated. Don't edit (proofs are okay). MAGIC COMMENT END -/
theorem bound_check2 (x y z : UInt32) : x ≤ 8 → y ≤ 8 → ((x) * (y) ≤ 64) := by auto?

/- Auto-generated. Don't edit (proofs are okay). MAGIC COMMENT END -/
theorem lemma_mul_upper_bound (x x_bound y y_bound : Int) :
    x ≤ x_bound → y ≤ y_bound → 0 ≤ x → 0 ≤ y → ((x) * (y) ≤ (x_bound) * (y_bound)) := by auto?

/- Auto-generated. Don't edit (proofs are okay). MAGIC COMMENT END -/
theorem lemma_mul_stay_positive (x y : Int) : 0 ≤ x → 0 ≤ y → (0 ≤ (x) * (y)) := by exact? --grind

/- Auto-generated. Don't edit (proofs are okay). MAGIC COMMENT END -/
theorem lemma_inequality_after_mul (x y z : Int) : x ≤ y → 0 ≤ z → ((x) * (z) ≤ (y) * (z)) := by auto?

/- Auto-generated. Don't edit (proofs are okay). MAGIC COMMENT END -/
theorem lemma_div_pos_is_pos (x d : Int) : 0 ≤ x → 0 < d → (0 ≤ x / d) := by auto?

/- Auto-generated. Don't edit (proofs are okay). MAGIC COMMENT END -/
theorem wrong_lemma_1 (x y z : Int) : x ≤ y → 0 ≤ z → ((x) * (z) < (y) * (z)) := by auto?

/- Auto-generated. Don't edit (proofs are okay). MAGIC COMMENT END -/
theorem wrong_lemma_2 (x y z : Int) : x > y → 3 ≤ z → ((y) * (z) > x) := by auto?

/- Auto-generated. Don't edit (proofs are okay). MAGIC COMMENT END -/
theorem test5_bound_checking (x y z : UInt32) :
    x ≤ 65535 → y ≤ 65535 → z ≤ 65535 → (0 ≤ (x) * (z) ∧ (x) * (z) ≤ ((65535) * (65535) : Nat)) := by auto?

/- Auto-generated. Don't edit (proofs are okay). MAGIC COMMENT END -/
theorem test6 (x y z : UInt32) : x < 4095 → ((x) * (x) + x = (x) * (x + 1) ∧ (x) * (y) = (y) * (x)) := by auto?

/- Auto-generated. Don't edit (proofs are okay). MAGIC COMMENT END -/
theorem test (x y z : Nat) : x < 4095 → ((((x) * (x) : Nat) + x : Nat) = ((x) * ((x + 1 : Nat)) : Nat)) := by
  auto?

/- Auto-generated. Don't edit (proofs are okay). MAGIC COMMENT END -/
theorem test_nonlinear (x : UInt32) : x < 4095 → ((x) * (x) + x = (x) * (x + 1)) := by auto?

/- Auto-generated. Don't edit (proofs are okay). MAGIC COMMENT END -/
theorem test_unexpected_vars (x y z : Int) : y = 0 → z = 0 → (z = 0 ∧ x + y = x) := by auto?

/- Auto-generated. Don't edit (proofs are okay). MAGIC COMMENT END -/
theorem test_new_vars (x : Int) : x = 5 → ((x) * (2) = 10) := by auto?

/- Auto-generated. Don't edit (proofs are okay). MAGIC COMMENT END -/
theorem test_nlarith1 (x y z : Int) : (x) * (y) = z ∧ ¬(x = 0) → (z % x = 0) := by grind

/- Auto-generated. Don't edit (proofs are okay). MAGIC COMMENT END -/
theorem test7_assert_a0 (z y x : Int) : (x + y) * (z) = (x) * (z) + (y) * (z) := by auto?

/- Auto-generated. Don't edit (proofs are okay). MAGIC COMMENT END -/
theorem test7_assert_a1 (z y x : Int) : (x - y) * (z) = (x) * (z) - (y) * (z) := by auto?

/- Auto-generated. Don't edit (proofs are okay). MAGIC COMMENT END -/
theorem test4_fails_assert_a0 (z x : UInt32) : (x) * (z) = (x) * (z) := by auto?
-- should FAIL in Verus? lost type cast to Int in Lean

/- Auto-generated. Don't edit (proofs are okay). MAGIC COMMENT END -/
theorem test_negative_assert_test6_a0 (z y x : Int) : (x + y) * (z) = (x) * (z) + (y) * (z) := by auto?

/- Auto-generated. Don't edit (proofs are okay). MAGIC COMMENT END -/
theorem test_negative_assert_test6_a1 : Bool.false := by auto?
-- should FAIL

end Nonlinear /- namespace -/

end VerusLean
